---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: "{{ .Values.ingressName }}-class"
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: {{ .Values.ingressName }}
