---
# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for Task, the build tool and task runner
#
# See: https://taskfile.dev

version: "3"

set: [pipefail]

includes:
  hf: tasks/helmfile
  tft: tasks/tft

tasks:
  default:
    cmds:
      - task: list

  list:
    desc: List available tasks
    cmds:
      - "{{.TASK_EXE}} --list"
