---
# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# These are Helmfile tasks for the Task runner:
#
# https://taskfile.dev
#
# Requirements:
#
# - Any UNIX shell
# - Helm
# - Helmfile
#
# Example:
#
# task hf:run -- status
#
# Set these variables to override the defaults:
#
# - HF_ENVIRONMENT - Helmfile environment
# - HF_K8S_CONTEXT - Kubernetes context
# - HF_PROFILE     - Root directory for the active Helmfile configuration

version: "3.38"

## Variables ##

vars:
  # Defaults
  DEFAULT_HF_CLI_EXE: helmfile
  DEFAULT_HF_ENVIRONMENT: default
  DEFAULT_HF_K8S_CONTEXT: minikube
  DEFAULT_HF_PROFILE: local

  # Variables to override

  CURRENT_HF_CLI_EXE:
    ref: "default .DEFAULT_HF_CLI_EXE .HELMFILE_CLI_EXE"

  CURRENT_HF_PROFILE:
    ref: "default .DEFAULT_HF_PROFILE .HF_PROFILE"

  CURRENT_HF_ENVIRONMENT:
    ref: "default .DEFAULT_HF_ENVIRONMENT .HF_ENVIRONMENT"

  CURRENT_HF_K8S_CONTEXT:
    ref: "default .DEFAULT_HF_K8S_CONTEXT .HF_K8S_CONTEXT"

  # Pre-set variables
  HF_ROOT_DIR: helmfile

  # Calculated variables
  HF_PROFILES_DIR: "{{.ROOT_DIR}}/{{.HF_ROOT_DIR}}"
  HF_FILE_PATH: "{{.HF_PROFILES_DIR}}/{{.CURRENT_HF_PROFILE}}/helmfile.yaml.gotmpl"
  HF_CLI_OPTS: "-e {{.CURRENT_HF_ENVIRONMENT}} --kube-context {{.CURRENT_HF_K8S_CONTEXT}} -f {{.HF_FILE_PATH}}"

env:
  HELMFILE_TEMPDIR: "{{.ROOT_DIR}}/tmp/helmfile"

tasks:
  apply:
    desc: Apply the changes between the Helmfile and the cluster
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} apply {{.HF_CLI_OPTS}}"

  destroy:
    desc: Destroy the releases on the cluster
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} destroy {{.HF_CLI_OPTS}}"

  diff:
    desc: Show the diff between the Helmfile and the cluster
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} diff {{.HF_CLI_OPTS}}"

  info:
    desc: Helmfile version
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} --version"

  lock:
    desc: Create a .helmfile.lock file
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} deps {{.HF_CLI_OPTS}}"

  run:
    desc: Run a Helmfile command
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} {{.CLI_ARGS}} {{.HF_CLI_OPTS}}"

  setup:
    desc: Setup Helmfile
    cmds:
      - "mkdir -p {{.HELMFILE_TEMPDIR}}"
      - "{{.CURRENT_HF_CLI_EXE}} init"

  sync:
    desc: Force the state of the cluster to match the Helmfile
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} sync {{.HF_CLI_OPTS}}"

  test:
    desc: Runs the Helm tests for the charts
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} test {{.HF_CLI_OPTS}}"

  context:list:
    desc: List Kubernetes contexts
    aliases:
      - contexts
    silent: true
    cmds:
      - for:
          var: K8S_CONTEXTS_LIST
        cmd: echo "{{.ITEM}}"
    vars:
      K8S_CONTEXTS:
        sh: kubectl config -o name get-contexts
      K8S_CONTEXTS_LIST:
        ref: 'splitList "\n" .K8S_CONTEXTS'

  profile:list:
    desc: List Helmfile profiles
    aliases:
      - profiles
    silent: true
    cmds:
      - for:
          var: HF_PROFILES_LIST
        cmd: echo "{{.ITEM}}"
    vars:
      HF_PROFILES:
        sh: ls -d {{.HF_PROFILES_DIR}}/*/ | xargs -n 1 basename
      HF_PROFILES_LIST:
        ref: 'splitList "\n" .HF_PROFILES'
