---
# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# These are Helmfile tasks for the Task runner:
#
# https://taskfile.dev
#
# Requirements:
#
# - Any UNIX shell
# - Helm
# - Helmfile
#
# Example:
#
# task hf:run -- status
#
# Set these variables to override the defaults:
#
# - HELMFILE_ENVIRONMENT - Helmfile environment
# - HELMFILE_K8S_CONTEXT - Kubernetes context
# - HELMFILE_PROFILE     - Root directory for the active Helmfile configuration

version: "3.38"

## Variables ##

vars:
  # Defaults
  DEFAULT_HELMFILE_CLI_EXE: helmfile
  DEFAULT_HELMFILE_ENVIRONMENT: default
  DEFAULT_HELMFILE_K8S_CONTEXT: minikube
  DEFAULT_HELMFILE_PROFILE: local

  # Variables to override

  CURRENT_HELMFILE_CLI_EXE:
    ref: "default .DEFAULT_HELMFILE_CLI_EXE .HELMFILE_CLI_EXE"

  CURRENT_HELMFILE_PROFILE:
    ref: "default .DEFAULT_HELMFILE_PROFILE .HELMFILE_PROFILE"

  CURRENT_HELMFILE_ENVIRONMENT:
    ref: "default .DEFAULT_HELMFILE_ENVIRONMENT .HELMFILE_ENVIRONMENT"

  CURRENT_HELMFILE_K8S_CONTEXT:
    ref: "default .DEFAULT_HELMFILE_K8S_CONTEXT .HELMFILE_K8S_CONTEXT"

  # Pre-set variables
  HELMFILE_ROOT_DIR: helmfile

  # Calculated variables
  HELMFILE_PROFILES_DIR: "{{.ROOT_DIR}}/{{.HELMFILE_ROOT_DIR}}"
  HELMFILE_FILE_PATH: "{{.HELMFILE_PROFILES_DIR}}/{{.CURRENT_HELMFILE_PROFILE}}/helmfile.yaml.gotmpl"
  HELMFILE_CLI_OPTS: "-e {{.CURRENT_HELMFILE_ENVIRONMENT}} --kube-context {{.CURRENT_HELMFILE_K8S_CONTEXT}} -f {{.HELMFILE_FILE_PATH}}"

env:
  HELMFILE_TEMPDIR: "{{.ROOT_DIR}}/tmp/helmfile"

tasks:
  apply:
    desc: Apply the changes between the Helmfile and the cluster
    cmds:
      - "{{.CURRENT_HELMFILE_CLI_EXE}} apply {{.HELMFILE_CLI_OPTS}}"

  destroy:
    desc: Destroy the releases on the cluster
    cmds:
      - "{{.CURRENT_HELMFILE_CLI_EXE}} destroy {{.HELMFILE_CLI_OPTS}}"

  diff:
    desc: Show the diff between the Helmfile and the cluster
    cmds:
      - "{{.CURRENT_HELMFILE_CLI_EXE}} diff {{.HELMFILE_CLI_OPTS}}"

  lock:
    desc: Create a .helmfile.lock file
    cmds:
      - "{{.CURRENT_HELMFILE_CLI_EXE}} deps {{.HELMFILE_CLI_OPTS}}"

  run:
    desc: Run a Helmfile command
    cmds:
      - "{{.CURRENT_HELMFILE_CLI_EXE}} {{.CLI_ARGS}} {{.HELMFILE_CLI_OPTS}}"

  sync:
    desc: Force the state of the cluster to match the Helmfile
    cmds:
      - "{{.CURRENT_HELMFILE_CLI_EXE}} sync {{.HELMFILE_CLI_OPTS}}"

  test:
    desc: Runs the post-deployment tests provided in the Helm charts
    cmds:
      - "{{.CURRENT_HELMFILE_CLI_EXE}} test {{.HELMFILE_CLI_OPTS}}"

  context:list:
    desc: List Kubernetes contexts
    aliases:
      - contexts
    silent: true
    cmds:
      - for:
          var: K8S_CONTEXTS_LIST
        cmd: echo "{{.ITEM}}"
    vars:
      K8S_CONTEXTS:
        sh: kubectl config -o name get-contexts
      K8S_CONTEXTS_LIST:
        ref: 'splitList "\n" .K8S_CONTEXTS'

  profile:list:
    desc: List Helmfile profiles
    aliases:
      - profiles
    silent: true
    cmds:
      - for:
          var: HELMFILE_PROFILES_LIST
        cmd: echo "{{.ITEM}}"
    vars:
      HELMFILE_PROFILES:
        sh: ls -d {{.HELMFILE_PROFILES_DIR}}/*/ | xargs -n 1 basename
      HELMFILE_PROFILES_LIST:
        ref: 'splitList "\n" .HELMFILE_PROFILES'
