---
# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# These are Helmfile tasks for the Task runner:
#
# https://taskfile.dev
#
# Requirements:
#
# - Any UNIX shell
# - Helm
# - Helmfile
#
# Example:
#
# task hf:run -- status
#
# Set these variables to override the defaults:
#
# - HF_ENVIRONMENT - Helmfile environment
# - HF_K8S_CONTEXT - Kubernetes context
# - HF_PROFILE     - Root directory for the active Helmfile configuration

version: "3.38"

## Variables ##

vars:
  # Defaults
  DEFAULT_HF_CLI_EXE: helmfile
  DEFAULT_HF_ENVIRONMENT: local-mkube
  DEFAULT_HF_K8S_CONTEXT: minikube
  DEFAULT_HF_PROFILE: main

  # Variables to override

  CURRENT_HF_CLI_EXE:
    ref: "default .DEFAULT_HF_CLI_EXE .HELMFILE_CLI_EXE"

  CURRENT_HF_PROFILE:
    ref: "default .DEFAULT_HF_PROFILE .HF_PROFILE"

  CURRENT_HF_ENVIRONMENT:
    ref: "default .DEFAULT_HF_ENVIRONMENT .HF_ENVIRONMENT"

  CURRENT_HF_K8S_CONTEXT:
    ref: "default .DEFAULT_HF_K8S_CONTEXT .HF_K8S_CONTEXT"

  # Pre-set variables
  HF_ROOT_DIR: helmfile

  # Calculated variables

  HF_PROFILES_DIR: "{{.ROOT_DIR}}/{{.HF_ROOT_DIR}}"
  HF_FILE_PATH: "{{.HF_PROFILES_DIR}}/{{.CURRENT_HF_PROFILE}}/helmfile.yaml.gotmpl"
  HF_CLI_OPTS: "-e {{.CURRENT_HF_ENVIRONMENT}} --kube-context {{.CURRENT_HF_K8S_CONTEXT}} -f {{.HF_FILE_PATH}}"

env:
  HELMFILE_TEMPDIR: "{{.ROOT_DIR}}/tmp/helmfile"

tasks:
  info:
    desc: Helmfile version
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} --version"

  lock:
    desc: Create a .helmfile.lock file
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} deps {{.HF_CLI_OPTS}}"

  run:
    desc: Run a Helmfile command
    cmds:
      - "{{.CURRENT_HF_CLI_EXE}} {{.CLI_ARGS}} {{.HF_CLI_OPTS}}"

  setup:
    desc: Setup Helmfile
    cmds:
      - "mkdir -p {{.HELMFILE_TEMPDIR}}"
      - "{{.CURRENT_HF_CLI_EXE}} init"
