apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.nodePoolName }}
spec:
  template:
    metadata:
      labels:
        product: eks-auto-example
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: {{ .Values.nodeClassName }}

      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["4", "8"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64", "amd64"]

  limits:
    cpu: {{ .Values.nodePoolCpuLimit }}
    memory: {{ .Values.nodePoolMemoryLimit }}
