# Default values for eks-nodes-standard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# Product name, for labels and tags
nodeTagProductName: "Unknown"

# Component name, for labels and tags
nodeTagComponentName: "Unknown"

# Environment name, for labels and tags
nodeTagEnvironmentName: "Unknown"

# Edition name, for labels and tags
nodeTagEditionName: ""

# Edition ID, for labels and tags
nodeTagEditionId: ""

# Name of the NodeClass
nodeClassName: "example-class"

# IAM role name for the NodeClass
nodeClassIamRole: ""

# KMS Key ARN for the NodeClass
nodeClassKmsKeyID: ""

# EC2 security group ID for the NodeClass
nodeClassSecurityGroupId: ""

# Ephemeral Storage size for the NodeClass
nodeClassEphemeralStorageSize: "80Gi"

# Ephemeral Storage IOPS for the NodeClass
nodeClassEphemeralStorageIops: "3000"

# Ephemeral Storage throughput for the NodeClass
nodeClassEphemeralStorageThroughput: "125"

# Name of the Node Pool
nodePoolName: "example-compute-od-amd64"
