apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: {{ .Values.nodeClassName }}
spec:
  role: {{ .Values.nodeClassIamRole }}
  subnetSelectorTerms:
    - tags:
        kubernetes.io/role/elb: "1"
  securityGroupSelectorTerms:
    - id: {{ .Values.nodeClassSecurityGroupId }}
  # ephemeralStorage:
  #   size: {{ .Values.nodeClassEphemeralStorageSize }}
